name: build

on:
  push:

permissions:
  contents: read
  checks: write

env:
  ARCHIVE_NAME: 'acme_r${{ github.run_number }}.xcarchive'

jobs:
  build:
    runs-on: macos-12
  
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: brew update
        run: brew update

      - name: setup xcbeautify
        run: brew install xcbeautify

      - name: build application
        run: >
          xcodebuild
          -project acme.xcodeproj
          -scheme acme
          -configuration Release
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData/acme
          -disableAutomaticPackageResolution
          -showBuildTimingSummary
          clean archive
          -archivePath dist/$ARCHIVE_NAME
          | tee > build.log

      - name: build report
        run: cat build.log | xcbeautify --renderer github-actions

      - name: report
        run: |
          mkdir dist/$ARCHIVE_NAME/Logs
          ls -la -R ~/Library/Developer/Xcode > dist/$ARCHIVE_NAME/Logs/Report.txt
          cp build.log dist/$ARCHIVE_NAME/Logs/build.log
          cp -R ~/Library/Developer/Xcode/DerivedData/acme/Logs dist/$ARCHIVE_NAME/Logs

      - name: compress archive
        run: tar -zcvf $ARCHIVE_NAME.tar.gz $ARCHIVE_NAME
        working-directory: ./dist

      - name: archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: dist/${{ env.ARCHIVE_NAME }}.tar.gz
